import type { Lesson } from "../types";

export const crossentropyLesson: Lesson = {
  slug: "crossentropy",
  title: "Cross-Entropy",
  subtitle: "분류 손실",
  kind: "crossentropy",
  trackOrder: 3.5,
  stage: "foundation",
  generatable: true,
  intro: [
    "분류에서는 Softmax 확률 p에 대해 CE = −log p[정답 클래스] 입니다.",
    "먼저 Softmax를 구한 뒤, 정답 칸의 −log를 구하세요. (소수 4자리)",
  ],
  formula: "CE = −log softmax(z)_y",
  exercises: [
    {
      id: "ce-1",
      title: "균등 Softmax",
      prompt: "z=[0,0] Softmax 먼저. 소수 4자리.",
      inputs: [{ label: "z", matrix: [[0, 0]] }],
      expected: [[0.5, 0.5]],
      decimals: 4,
      shapeHint: "[1×2]",
      formulaHint: "같으면 1/2",
    },
    {
      id: "ce-2",
      title: "−log 0.5",
      prompt: "정답이 class0이고 p0=0.5일 때 CE. −ln(0.5)≈0.6931",
      inputs: [{ label: "p", matrix: [[0.5, 0.5]] }],
      expected: [[0.6931]],
      decimals: 4,
      shapeHint: "스칼라",
      formulaHint: "−log 0.5",
    },
    {
      id: "ce-3",
      title: "한쪽으로 쏠린 로짓",
      prompt: "z=[2,0] Softmax (소수 4자리)",
      inputs: [{ label: "z", matrix: [[2, 0]] }],
      expected: [[0.8808, 0.1192]],
      decimals: 4,
      shapeHint: "[1×2]",
      formulaHint: "max=2 빼고 exp",
    },
    {
      id: "ce-4",
      title: "정답=0일 때 CE",
      prompt: "p≈[0.8808, 0.1192], y=0 → −log 0.8808 ≈ 0.1270",
      inputs: [{ label: "p", matrix: [[0.8808, 0.1192]] }],
      expected: [[0.127]],
      decimals: 3,
      shapeHint: "스칼라",
      formulaHint: "−ln(0.8808)",
    },
    {
      id: "ce-5",
      title: "정답=1일 때 CE",
      prompt: "같은 p에서 y=1 → −log 0.1192 ≈ 2.127",
      inputs: [{ label: "p", matrix: [[0.8808, 0.1192]] }],
      expected: [[2.127]],
      decimals: 3,
      shapeHint: "스칼라",
      formulaHint: "틀리면 손실이 커집니다",
    },
  ],
};
